// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

type Article struct {
	StoryID          int     `json:"story_id"`
	Content          *string `json:"content"`
	Title            *string `json:"title"`
	Excerpt          *string `json:"excerpt"`
	Byline           *string `json:"byline"`
	ExtractionFailed bool    `json:"extraction_failed"`
	FetchedAt        int64   `json:"fetched_at"`
}

type Comment struct {
	ID        int     `json:"id"`
	StoryID   int     `json:"story_id"`
	ParentID  *int    `json:"parent_id"`
	By        *string `json:"by"`
	Text      *string `json:"text"`
	Time      int64   `json:"time"`
	Dead      bool    `json:"dead"`
	Deleted   bool    `json:"deleted"`
	FetchedAt int64   `json:"fetched_at"`
}

type Ranking struct {
	StoryID    int     `json:"story_id"`
	Period     string  `json:"period"`
	Score      float64 `json:"score"`
	ComputedAt int64   `json:"computed_at"`
}

type Session struct {
	Token     string `json:"token"`
	UserSub   string `json:"user_sub"`
	UserInfo  string `json:"user_info"`
	ExpiresAt int64  `json:"expires_at"`
}

type Story struct {
	ID          int     `json:"id"`
	Title       string  `json:"title"`
	URL         *string `json:"url"`
	Text        *string `json:"text"`
	Score       int     `json:"score"`
	By          string  `json:"by"`
	Time        int64   `json:"time"`
	Descendants int     `json:"descendants"`
	Type        string  `json:"type"`
	FetchedAt   int64   `json:"fetched_at"`
	Rank        *int    `json:"rank"`
	Dead        bool    `json:"dead"`
}
