// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package store

import (
	"context"
)

const cleanExpiredSessions = `-- name: CleanExpiredSessions :exec
DELETE FROM sessions WHERE expires_at <= ?
`

func (q *Queries) CleanExpiredSessions(ctx context.Context, db DBTX, expiresAt int64) error {
	_, err := db.ExecContext(ctx, cleanExpiredSessions, expiresAt)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (token, user_sub, user_info, expires_at) VALUES (?, ?, ?, ?)
`

type CreateSessionParams struct {
	Token     string `json:"token"`
	UserSub   string `json:"user_sub"`
	UserInfo  string `json:"user_info"`
	ExpiresAt int64  `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, db DBTX, arg CreateSessionParams) error {
	_, err := db.ExecContext(ctx, createSession,
		arg.Token,
		arg.UserSub,
		arg.UserInfo,
		arg.ExpiresAt,
	)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token = ?
`

func (q *Queries) DeleteSession(ctx context.Context, db DBTX, token string) error {
	_, err := db.ExecContext(ctx, deleteSession, token)
	return err
}

const getSession = `-- name: GetSession :one
SELECT token, user_sub, user_info, expires_at
FROM sessions WHERE token = ? AND expires_at > ?
`

type GetSessionParams struct {
	Token     string `json:"token"`
	ExpiresAt int64  `json:"expires_at"`
}

func (q *Queries) GetSession(ctx context.Context, db DBTX, arg GetSessionParams) (*Session, error) {
	row := db.QueryRowContext(ctx, getSession, arg.Token, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.Token,
		&i.UserSub,
		&i.UserInfo,
		&i.ExpiresAt,
	)
	return &i, err
}
