// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stars.sql

package store

import (
	"context"
)

const deleteStar = `-- name: DeleteStar :exec
DELETE FROM stars WHERE user_sub = ? AND story_id = ?
`

type DeleteStarParams struct {
	UserSub string `json:"user_sub"`
	StoryID int    `json:"story_id"`
}

func (q *Queries) DeleteStar(ctx context.Context, db DBTX, arg DeleteStarParams) error {
	_, err := db.ExecContext(ctx, deleteStar, arg.UserSub, arg.StoryID)
	return err
}

const getStar = `-- name: GetStar :one
SELECT user_sub, story_id, starred_at FROM stars WHERE user_sub = ? AND story_id = ?
`

type GetStarParams struct {
	UserSub string `json:"user_sub"`
	StoryID int    `json:"story_id"`
}

func (q *Queries) GetStar(ctx context.Context, db DBTX, arg GetStarParams) (*Star, error) {
	row := db.QueryRowContext(ctx, getStar, arg.UserSub, arg.StoryID)
	var i Star
	err := row.Scan(&i.UserSub, &i.StoryID, &i.StarredAt)
	return &i, err
}

const listStarredStoryIDs = `-- name: ListStarredStoryIDs :many
SELECT DISTINCT story_id FROM stars
`

func (q *Queries) ListStarredStoryIDs(ctx context.Context, db DBTX) ([]int, error) {
	rows, err := db.QueryContext(ctx, listStarredStoryIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int{}
	for rows.Next() {
		var story_id int
		if err := rows.Scan(&story_id); err != nil {
			return nil, err
		}
		items = append(items, story_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStarsByUser = `-- name: ListStarsByUser :many
SELECT user_sub, story_id, starred_at FROM stars WHERE user_sub = ?
`

func (q *Queries) ListStarsByUser(ctx context.Context, db DBTX, userSub string) ([]*Star, error) {
	rows, err := db.QueryContext(ctx, listStarsByUser, userSub)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Star{}
	for rows.Next() {
		var i Star
		if err := rows.Scan(&i.UserSub, &i.StoryID, &i.StarredAt); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertStar = `-- name: UpsertStar :exec
INSERT INTO stars (user_sub, story_id, starred_at) VALUES (?, ?, ?)
ON CONFLICT(user_sub, story_id) DO UPDATE SET starred_at = excluded.starred_at
`

type UpsertStarParams struct {
	UserSub   string `json:"user_sub"`
	StoryID   int    `json:"story_id"`
	StarredAt int64  `json:"starred_at"`
}

func (q *Queries) UpsertStar(ctx context.Context, db DBTX, arg UpsertStarParams) error {
	_, err := db.ExecContext(ctx, upsertStar, arg.UserSub, arg.StoryID, arg.StarredAt)
	return err
}
